# This is a basic workflow that is manually triggered

name: Deploy Surge

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 12
      - name: Install surge
        run: npm install -g surge
      - name: Install packages
        # clean install for our vm
        run: npm ci
      - name: Build command
        run: npm run build
      - name: Deploy to surge
        run: surge ./build saad-saif-covid-tracker-bootcamp2020.surge.sh --token ${{ secrets.SURGE_TOKEN }}
